# Assignment 3
1. Import the MELBOURNE_HOUSE_PRICES_LESS.csv dataset
2. Extract all the values where price column is not null from the dataset to a new variable
3. Extract all the values where price column is null from the dataset to a new variable
4. Clean the dataset so it deosn't have any null value again using any method 
5. Compute the sum, mean of the price column on the dataset
6. Get the house with the lowest price and with the highest price

In [1]:
import numpy as np
import pandas as pd

In [3]:
# Question 1
data =pd.read_csv('C:\\Users\\ALIYU\\Desktop\\Datasets\\MELBOURNE_HOUSE_PRICES_LESS.csv')
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [8]:
# 2. Extract all the values where price column is not null from the dataset to a new variable

data[data['Price'].notnull()]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63016,Frankston,4/34 Petrie St,2,u,347700.0,SP,Aquire,31/03/2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63017,Preston,229 Murray Rd,3,h,808000.0,S,RW,31/03/2018,3072,Northern Metropolitan,14577,8.4,Darebin City Council
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council

In [10]:
# 3. Extract all the values where price column is null from the dataset to a new variable

data[data['Price'].isnull()]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
8,Albanvale,1 Jackson Cct,6,h,NaN,PI,hockingstuart,1/04/2017,3021,Western Metropolitan,1899,14.0,Brimbank City Council
15,Altona Meadows,57 Tatman Dr,4,h,NaN,SN,Barry,1/04/2017,3028,Western Metropolitan,7630,15.5,Hobsons Bay City Council
24,Ashburton,1 Pitt St,4,h,NaN,S,Jellis,1/04/2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
29,Attwood,46 Threadneedle St,4,h,NaN,SN,Barry,1/04/2017,3049,Northern Metropolitan,1130,16.5,Hume City Council
38,Balwyn North,12 Agnes Av,3,h,NaN,SP,Fletchers,1/04/2017,3104,Southern Metropolitan,7809,9.7,Boroondara City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63001,Wyndham Vale,15 Yaltara Dr,3,h,NaN,S,hockingstuart,30/12/2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63008,Yarraville,4/247 Williamstown Rd,3,t,NaN,S,Jas,30/12/2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63010,Burwood,29 Summit Rd,4,h,NaN,PN,@Realty,31/03/2018,3125,Southern Metropolitan,5678,10.4,Monash City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [14]:
clearn = data['Price'].isnull().mean()
clearn

0.23150278469765007

In [18]:
# 4. Clean the dataset so it deosn't have any null value again using any method 

# data.dropna(inplace=True)
data.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price            14590
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [24]:
clearn = data['Price'].isnull().sum()
data.fillna(clearn, inplace=True)

In [25]:
data.isnull().sum()

Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Postcode         0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
dtype: int64

In [26]:
# 5. Compute the sum, mean of the price column on the dataset
sum_price=data['Price'].sum()


sum_price

48544073630.0

In [27]:
mean_price=data['Price'].mean()

mean_price

770259.6453675642

In [36]:
# 6. Get the house with the lowest price and with the highest price
min_house_price = data['Price'].idxmin

min_house_price

8

In [34]:
House_with_lowest_price =data.loc[min_house_price]

House_with_lowest_price

Suburb                       Albanvale
Address                  1 Jackson Cct
Rooms                                6
Type                                 h
Price                          14590.0
Method                              PI
SellerG                  hockingstuart
Date                         1/04/2017
Postcode                          3021
Regionname        Western Metropolitan
Propertycount                     1899
Distance                          14.0
CouncilArea      Brimbank City Council
Name: 8, dtype: object

In [35]:
# Highest price

max_price = data['Price'].idxmax()
max_price

59166

In [32]:
House_with_Highest_price =data.loc[max_price]

House_with_Highest_price

Suburb                        Brighton
Address                      6 Cole St
Rooms                                4
Type                                 h
Price                       11200000.0
Method                              VB
SellerG                  hockingstuart
Date                        28/10/2017
Postcode                          3186
Regionname       Southern Metropolitan
Propertycount                    10579
Distance                          10.5
CouncilArea       Bayside City Council
Name: 59166, dtype: object